services:
  db:
    container_name: ssn_pg
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    networks:
      - ssn_net

  redis:
    container_name: ssn_redis
    image: redis:7.4.2-alpine
    restart: always
    env_file:
      - .env
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data
    networks:
      - ssn_net
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M

  backend:
    container_name: ssn_backend
    build: .
    restart: always
    ports:
      - 8000:8000
    networks:
      - ssn_net
    env_file:
      - .env

networks:
  ssn_net:
